[FEAT] 종료된 챌린지 UI 구현
alloon-project/photi-ios pull request #154
Opened 2024-10-24 08:20 UTC by lemona-97

## 관련 이슈

- #115 

## 작업 설명

종료된 챌린지 UI 작업입니다.

해당 UI에는 Search Card의 off 타입이 적용되는데,  하나의 Search Card로 내부에 on off를 넣는것은 여러 요소(높이 & 데이터)를 고려해서 구현 할 때 소요가 더 크다고 생각하여 SearchCardOffTypeCell을 따로 구현했습니다 
(SearchCardOnTypeCell 을 추후에 구현하려합니다)

## 스크린샷

<img src = "https://github.com/user-attachments/assets/771bb42a-f98e-4c27-b8d4-6adc4fafe102" width=200>

## PR 특이 사항

- API연결 시 수정할 내용들이 포함되어있습니다 고려해서 리뷰 부탁드립니다!

2024-10-24 14:27 UTC, jungseokyoung-cloud requested changes
몇가지만 확인 부탁드립니다! 
추가적으로 on은 어디서 쓰이는건가요? 

현재는 너무 데모(?)코드(컬러..)가 많아서, 좀 더 완성되면 그때는 디바이스에서 돌려보면서 체크해보겠습니다!

2024-10-24 14:27 UTC, jungseokyoung-cloud commented on Projects/DesignSystem/Resources/Images/Images.xcassets/pinking_gray.imageset/background.png
혹시 이거 삭제하고 다시 받으신 이유가 있나요?

2024-10-24 14:27 UTC, jungseokyoung-cloud commented on Projects/DesignSystem/Sources/Card/Search/SearchCardOffTypeCell.swift
> +    view.layer.shadowRadius = 8
view에 shadow 추가해주는거 이전에 extension으로 분리했습니다.

2024-10-24 14:27 UTC, jungseokyoung-cloud commented on Projects/Presentation/MyPage/Implementations/FinishedChallange/FinishedChallangeViewController.swift
> +    collectionView.isPagingEnabled = false
이건 isPagingEnabled는 default로 false여서 필요없습니다!
또한, snapKit사용하면 translatesAutor..도 필요없습니다. 

마지막으로 alwatsBounceVertical은 어떤 의도로 false로 해두신건가요?

2024-10-24 14:27 UTC, jungseokyoung-cloud commented on Projects/Presentation/MyPage/Implementations/FinishedChallange/FinishedChallangeViewController.swift
> +    let collectionView = UICollectionView(frame: .zero, collectionViewLayout: self.layout)
self 에 접근하기 위해서 lazy키워드를 사용하셨는데, 
lazy말고 클로져 안에 GridLayout코드를 옮기면 lazy가 필요없어보이는데, lazy를 사용하신 이유가 있나요? 
궁금해서 여쭤봅니다.

2024-10-24 14:27 UTC, jungseokyoung-cloud commented on Projects/Presentation/MyPage/Implementations/FinishedChallange/GridCollectionViewFlowLayout.swift
> +final class GridCollectionViewFlowLayout: UICollectionViewFlowLayout {
이거는 왜 따로 빼신건가요?? 
numberOfColums도 rotioHeightToWidth도 둘다 안쓰이는 변수인데 굳이 cellSpacing을 위해서였다면, `minimumLineSpacing`하고, `minimumInteritemSpacing`만 외부에서 설정해줘도 되는거 아닌가요?

2024-10-27 14:58 UTC, jungseokyoung-cloud commented on Projects/DesignSystem/Sources/Card/Search/SearchCardOffTypeCell.swift
> +public final class SearchCardOffTypeCell: UICollectionViewCell {
개인적으로 디저이너 분들이 명시해놓은 네이밍도 좋지만, 저희 프로젝트에 적절한 네이밍으로 전환하는것도 좋아보입니다! 개인적으로 어떤 역할을 하는 건지 저것만 보고는 모를꺼 같아요!

2024-10-27 15:00 UTC, lemona-97 commented on Projects/DesignSystem/Sources/Card/Search/SearchCardOffTypeCell.swift
> +public final class SearchCardOffTypeCell: UICollectionViewCell {
음.. 의견 감사합니다 수정할게요!

2024-10-28 03:54 UTC, merged